title: Joyce Ovalle
description: The University of Texas at Austin
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
