on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: 16  # Specify Node.js version 16
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Build
        run: script/bootstrap
      - name: Test
        run: script/cibuild
